version: '3.8'

services:
  mongodb:
    image: mongo:5.0.9 
    container_name: mongodb
    ports:
      - "27019:27017"
    restart: always  
    volumes:
      - /projects/Esoft/WildLife-Applicaion-Dashboard/db_backup:/data/db

